"""NL Protocol core subpackage -- shared types, errors, config, and interfaces."""
from __future__ import annotations

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
from nl_protocol.core.config import NLProviderConfig

# ---------------------------------------------------------------------------
# Error hierarchy
# ---------------------------------------------------------------------------
from nl_protocol.core.errors import (
    # NL-E4xx
    ActionBlocked,
    AgentRevoked,
    AgentRevokedByDetection,
    AgentSuspended,
    AIDExpired,
    AmbiguousReference,
    AttestationSignatureInvalid,
    AuditError,
    AuditQueryDenied,
    AuditWriteFailure,
    # Category bases
    AuthenticationError,
    AuthorizationError,
    CapabilityNotGranted,
    # NL-E5xx
    ChainIntegrityFailure,
    ConcurrentLimit,
    ContextMismatch,
    DefenseError,
    DelegationDepthExceeded,
    DelegationSubsetViolation,
    DelegationTokenExpired,
    DelegationTokenRevoked,
    DelegationUseLimit,
    DetectionError,
    EnvironmentRestricted,
    EvasionDetected,
    ExecutionError,
    ExecutionTimeout,
    ExpiredAttestation,
    FederationActionNotAllowed,
    FederationAgreementExpired,
    FederationError,
    FederationPartnerUnavailable,
    HoneypotTriggered,
    HumanApprovalRequired,
    InterceptorUnavailable,
    # NL-E1xx
    InvalidAgent,
    InvalidDelegationToken,
    InvalidPlaceholder,
    InvalidTimestamp,
    IsolationFailure,
    # NL-E8xx
    MalformedMessage,
    MessageTooLarge,
    NLProtocolError,
    # NL-E2xx
    NoScopeGrant,
    ProviderNotConfigured,
    ProviderUnavailable,
    ReplayDetectedAuth,
    ReplayDetectedTransport,
    SanitizationFailure,
    ScopeExpired,
    SecretNotFound,
    # NL-E6xx
    ThreatLevelExceeded,
    TransportError,
    TrustLevelInsufficient,
    # NL-E3xx
    UnknownActionType,
    UnknownMessageType,
    # NL-E7xx
    UnknownTrustDomain,
    UnsupportedMediaType,
    UseLimitExceeded,
    VersionMismatch,
)

# ---------------------------------------------------------------------------
# Abstract interfaces (Protocol classes)
# ---------------------------------------------------------------------------
from nl_protocol.core.interfaces import (
    AgentRegistry,
    AuditStore,
    DelegationStore,
    InMemoryAgentRegistry,
    InMemoryAuditStore,
    InMemoryDelegationStore,
    InMemoryNonceStore,
    InMemoryScopeGrantStore,
    # In-memory implementations
    InMemorySecretStore,
    NonceStore,
    ScopeGrantStore,
    SecretStore,
)

# ---------------------------------------------------------------------------
# Domain types & enums
# ---------------------------------------------------------------------------
from nl_protocol.core.types import (
    AID,
    ActionError,
    ActionPayload,
    ActionRequest,
    ActionResponse,
    ActionResult,
    ActionType,
    AgentURI,
    AuditRecord,
    DelegationScope,
    DelegationToken,
    LifecycleState,
    ScopeConditions,
    ScopeGrant,
    SecretRef,
    SecretValue,
    ThreatLevel,
    TrustLevel,
)

__all__ = [
    # Types
    "AgentURI",
    "SecretRef",
    "SecretValue",
    "TrustLevel",
    "LifecycleState",
    "ActionType",
    "ThreatLevel",
    "AID",
    "ScopeGrant",
    "ScopeConditions",
    "ActionRequest",
    "ActionPayload",
    "ActionResponse",
    "ActionResult",
    "ActionError",
    "DelegationToken",
    "DelegationScope",
    "AuditRecord",
    # Errors
    "NLProtocolError",
    "AuthenticationError",
    "AuthorizationError",
    "ExecutionError",
    "DefenseError",
    "AuditError",
    "DetectionError",
    "FederationError",
    "TransportError",
    "InvalidAgent",
    "ExpiredAttestation",
    "TrustLevelInsufficient",
    "AgentSuspended",
    "AgentRevoked",
    "AIDExpired",
    "AttestationSignatureInvalid",
    "ReplayDetectedAuth",
    "CapabilityNotGranted",
    "NoScopeGrant",
    "ScopeExpired",
    "UseLimitExceeded",
    "EnvironmentRestricted",
    "HumanApprovalRequired",
    "ContextMismatch",
    "ConcurrentLimit",
    "UnknownActionType",
    "InvalidPlaceholder",
    "SecretNotFound",
    "ExecutionTimeout",
    "AmbiguousReference",
    "ProviderUnavailable",
    "ProviderNotConfigured",
    "IsolationFailure",
    "SanitizationFailure",
    "ActionBlocked",
    "EvasionDetected",
    "InterceptorUnavailable",
    "ChainIntegrityFailure",
    "AuditQueryDenied",
    "AuditWriteFailure",
    "ThreatLevelExceeded",
    "AgentRevokedByDetection",
    "HoneypotTriggered",
    "UnknownTrustDomain",
    "FederationAgreementExpired",
    "DelegationSubsetViolation",
    "DelegationDepthExceeded",
    "InvalidDelegationToken",
    "DelegationTokenExpired",
    "DelegationUseLimit",
    "DelegationTokenRevoked",
    "FederationPartnerUnavailable",
    "FederationActionNotAllowed",
    "MalformedMessage",
    "VersionMismatch",
    "ReplayDetectedTransport",
    "MessageTooLarge",
    "UnsupportedMediaType",
    "InvalidTimestamp",
    "UnknownMessageType",
    # Config
    "NLProviderConfig",
    # Interfaces
    "SecretStore",
    "AgentRegistry",
    "ScopeGrantStore",
    "AuditStore",
    "NonceStore",
    "DelegationStore",
    "InMemorySecretStore",
    "InMemoryAgentRegistry",
    "InMemoryScopeGrantStore",
    "InMemoryAuditStore",
    "InMemoryNonceStore",
    "InMemoryDelegationStore",
]
